name: Deploy Application on Cloud Run
on: [push]
jobs:
  Deploy-CloudRun:
    env:
      REGION: us-east1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: echo ${{github.repository}}

      - name: "Google Cloud Authentication"
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{secrets.GCP_SA_KEY}}'


      - run: gcloud info
      
      - name: Docker Auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      
      - name: Build e Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: us-east1-docker.pkg.dev/vertexai-practice-443200/docker-registry/generate-alt-description:latest
      
      - uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          region: ${{ env.REGION }}
          image: us-east1-docker.pkg.dev/vertexai-practice-443200/docker-registry/generate-alt-description:latest
          service: generate-alt-description-svc
          
          
          
          
        


      

          
      